version: "3.9"

services:
  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379" 
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  
  chat-service:
    build: ./chat-service
    ports:
      - "3000:3000"
    depends_on: 
      - redis
      - rabbitmq
    environment:
        REDIS_HOST: redis
        REDIS_PORT: 6379
        RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
